default_agent: agent_simple
agents:
  agent_simple:
    name: agent_simple
    language: python
    node_version: '20'
    entrypoint: /home/ubuntu/environment/hackthon/agent/agent_simple.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/ubuntu/environment/hackthon/agent
    aws:
      execution_role: arn:aws:iam::396608791379:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-fc69ed8f10
      execution_role_auto_create: false
      account: '396608791379'
      region: us-east-1
      ecr_repository: 396608791379.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent_simple
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent_simple-jfQ3MB85h1
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:396608791379:runtime/agent_simple-jfQ3MB85h1
      agent_session_id: 356676f3-08e4-4f19-b8cd-07b142f5b415
    codebuild:
      project_name: bedrock-agentcore-agent_simple-builder
      execution_role: arn:aws:iam::396608791379:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-fc69ed8f10
      source_bucket: bedrock-agentcore-codebuild-sources-396608791379-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
